-- Canonical cross-protocol event schema. Raw token amounts remain decimal strings
-- because uint256 values may exceed signed 64/128-bit database types.
CREATE TABLE accountability_events (
    schema_version VARCHAR NOT NULL,
    accountability_event_id VARCHAR PRIMARY KEY,
    oracle_network VARCHAR NOT NULL,
    mechanism_family VARCHAR NOT NULL,
    security_chain VARCHAR NOT NULL,
    delivery_chain VARCHAR,
    accountability_unit_type VARCHAR NOT NULL,
    accountability_unit_id VARCHAR NOT NULL,
    event_granularity VARCHAR NOT NULL,
    event_time_unix BIGINT,
    actor VARCHAR,
    actor_role VARCHAR,
    counterparty VARCHAR,
    counterparty_role VARCHAR,
    reward_class VARCHAR,
    reward_amount_raw VARCHAR,
    reward_asset VARCHAR,
    reward_asset_decimals SMALLINT,
    reward_accrual_time_unix BIGINT,
    reward_payment_time_unix BIGINT,
    penalty_class VARCHAR,
    principal_slashed_raw VARCHAR,
    bond_forfeited_raw VARCHAR,
    fee_forfeited_raw VARCHAR,
    reward_forfeited_raw VARCHAR,
    penalty_asset VARCHAR,
    penalty_asset_decimals SMALLINT,
    nonmonetary_penalty VARCHAR,
    principal_locked_raw VARCHAR,
    principal_returned_raw VARCHAR,
    principal_asset VARCHAR,
    principal_asset_decimals SMALLINT,
    truth_basis VARCHAR NOT NULL,
    outcome_status VARCHAR NOT NULL,
    external_truth_available BOOLEAN NOT NULL,
    service_window_seconds BIGINT,
    service_threshold_seconds BIGINT,
    source_event VARCHAR NOT NULL,
    source_tx VARCHAR,
    source_block BIGINT,
    source_log_index BIGINT,
    source_contract VARCHAR,
    rule_id VARCHAR NOT NULL,
    parameter_version VARCHAR,
    observability_grade VARCHAR NOT NULL,
    confidence_grade VARCHAR NOT NULL,
    native_table VARCHAR NOT NULL,
    sample_tier VARCHAR,
    interpretation_note VARCHAR
);
